name = "Simple Papaya"
description = "Fork of Papaya: A clean Zola theme for blogging and projects"
license = "MIT"
# The minimum version of Zola required
min_version = "0.16.1"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
env = "$ZOLA_ENV"
papaya_date_format = "%B %e, %Y"
papaya_menu_links = []

[author]
name = "Arthur Tadier"
homepage = "https://atadier.net"
